# Generated by Codex on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("core", "0002_botcontrol"),
	]

	operations = [
		migrations.CreateModel(
			name="AppSetting",
			fields=[
				("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("key", models.CharField(max_length=128, unique=True)),
				("value", models.CharField(max_length=255)),
				("description", models.TextField(blank=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
			],
			options={
				"db_table": "app_settings",
			},
		),
	]
