# Generated by Codex on 2026-05-03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		("core", "0003_appsetting"),
	]

	operations = [
		migrations.CreateModel(
			name="DustSignalReview",
			fields=[
				("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("symbol", models.CharField(blank=True, default="", max_length=32)),
				("asset", models.CharField(blank=True, default="", max_length=32)),
				("reason", models.TextField(blank=True, default="")),
				("event_type", models.CharField(blank=True, default="", max_length=64)),
				("severity", models.CharField(blank=True, default="", max_length=32)),
				("status", models.CharField(choices=[("pending", "Pending"), ("reviewed", "Reviewed"), ("ignored", "Ignored"), ("review_later", "Review later"), ("needs_manual_correction", "Needs manual correction"), ("external_or_earn", "External or Earn")], default="pending", max_length=32)),
				("note", models.TextField(blank=True)),
				("reviewed_at", models.DateTimeField(blank=True, null=True)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
				("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
			],
			options={
				"db_table": "dust_signal_reviews",
			},
		),
		migrations.AddConstraint(
			model_name="dustsignalreview",
			constraint=models.UniqueConstraint(fields=("symbol", "asset", "reason", "event_type", "severity"), name="unique_dust_signal_review_identity"),
		),
	]
