# Generated by Django 4.1.3 on 2022-11-30 01:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(allow_unicode=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_quote', models.FloatField(default=0.0)),
                ('denominator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denominator', to='currencyconverter.currency')),
                ('numerator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numerator', to='currencyconverter.currency')),
            ],
        ),
    ]
