# Generated by Django 4.1.3 on 2022-11-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(allow_unicode=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
